<?php

$routes = [
    'login' => '../public/index.php',
    'admin_dashboard' => '../resources/views/admin/dashboard.php',
    'user_dashboard' => '../resources/views/user/dashboard.php',
    'logout' => '../app/controller/logout.php',
    'setting_admin' => '../resources/views/admin/Setting.php',
    'setting_user' => '../resources/views/user/Setting.php',
    'pelatih_admin' => '../resources/views/admin/pelatih.php',
    'struktur' => '../resources/views/admin/struktur.php',
    'absensi' => '../resources/views/admin/absensi.php',
    'laporan' => '../resources/views/admin/laporan.php',
    'simpan_pelatih' => '../app/controller/simpan_pelatih.php',
    'hapus_pelatih' => '../app/controller/hapus_pelatih.php',
    'detail_pelatih' => '../app/controller/detail_pelatih.php',
    'edit_pelatih' => '../app/controller/edit_pelatih.php',
    'penilaian' => '../resources/views/admin/penilaian.php',
    'simpan_penilaian' => '../app/controller/simpan_penilaian.php',
    'sekolah_admin' => '../resources/views/admin/sekolah.php',
    'detail_penilaian' => '../app/controller/detail_penilaian.php',
    'simpan_sekolah' => '../app/controller/simpan_sekolah.php',
    'hapus_sekolah' => '../app/controller/hapus_sekolah.php',
    'detail_sekolah' => '../app/controller/detail_sekolah.php',
    'simpan_murid' => '../app/controller/simpan_murid.php',
    'hapus_murid' => '../app/controller/hapus_murid.php',
    'update_sekolah' => '../app/controller/update_sekolah.php',
];